import type { FastifyInstance } from 'fastify';
import PDFDocument from 'pdfkit';
import { requireApiKey } from '../plugins/auth.js';
import { scan } from '@nxtg/faultline/cli/scan.js';
import type { ScanResult } from '@nxtg/faultline/cli/scan.js';

const BODY_SCHEMA = {
  type: 'object',
  required: ['text'],
  properties: {
    text: { type: 'string', minLength: 1, maxLength: 50000 },
    provider: {
      type: 'string',
      enum: ['gemini', 'openai', 'claude', 'perplexity', 'mock'],
    },
    projectName: { type: 'string', maxLength: 200 },
  },
  additionalProperties: false,
} as const;

interface ReportBody {
  text: string;
  provider?: 'gemini' | 'openai' | 'claude' | 'perplexity' | 'mock';
  projectName?: string;
}

function statusToVerdict(status: string): string {
  switch (status) {
    case 'supported': return 'Verified';
    case 'contradicted': return 'Contradicted';
    case 'mixed': return 'Partial';
    case 'unverified': return 'Unverified';
    case 'skipped': return 'Skipped';
    default: return 'Unknown';
  }
}

function riskColor(risk: string): string {
  switch (risk) {
    case 'critical': return 'Unacceptable (EU AI Act)';
    case 'high': return 'High Risk';
    case 'medium': return 'Limited Risk';
    default: return 'Minimal Risk';
  }
}

function buildPdf(result: ScanResult, projectName: string, scanDate: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const BRAND_BLUE = '#1a56db';
    const GRAY = '#6b7280';
    const DARK = '#111827';
    const RED = '#dc2626';
    const ORANGE = '#d97706';
    const GREEN = '#16a34a';

    const riskBadge = result.overallRisk === 'critical' ? RED
      : result.overallRisk === 'high' ? ORANGE
      : result.overallRisk === 'medium' ? ORANGE
      : GREEN;

    // ── COVER PAGE ──────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 8).fill(BRAND_BLUE);

    doc.moveDown(4);
    doc.font('Helvetica-Bold').fontSize(26).fillColor(DARK)
      .text('AI Trust & Safety', { align: 'center' })
      .text('Compliance Report', { align: 'center' });

    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(12).fillColor(GRAY)
      .text('Generated by Faultline Pro', { align: 'center' });

    doc.moveDown(2);

    // Metadata box
    const boxX = 80;
    const boxW = doc.page.width - 160;
    doc.roundedRect(boxX, doc.y, boxW, 100, 6).strokeColor('#e5e7eb').stroke();

    const metaTop = doc.y + 16;
    doc.font('Helvetica').fontSize(10).fillColor(GRAY);
    doc.text('Project', boxX + 20, metaTop);
    doc.text('Date', boxX + 20, metaTop + 24);
    doc.text('Provider', boxX + 20, metaTop + 48);
    doc.text('Overall Risk', boxX + 20, metaTop + 72);

    doc.font('Helvetica-Bold').fontSize(10).fillColor(DARK);
    doc.text(projectName || 'Untitled Scan', boxX + 120, metaTop);
    doc.text(scanDate, boxX + 120, metaTop + 24);
    doc.text(result.provider, boxX + 120, metaTop + 48);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(riskBadge);
    doc.text(result.overallRisk.toUpperCase(), boxX + 120, metaTop + 72);

    doc.moveDown(7);
    doc.rect(0, doc.page.height - 30, doc.page.width, 30).fill('#f9fafb');
    doc.font('Helvetica').fontSize(9).fillColor(GRAY)
      .text('Generated by Faultline Pro — faultline.nxtg.ai', 0, doc.page.height - 20, { align: 'center' });

    // ── EXECUTIVE SUMMARY ───────────────────────────────────────────────────
    doc.addPage();
    doc.rect(0, 0, doc.page.width, 8).fill(BRAND_BLUE);
    doc.moveDown(1.5);

    doc.font('Helvetica-Bold').fontSize(16).fillColor(DARK)
      .text('Executive Summary', 50);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);

    const claims = result.claims;
    const verifs = Object.values(result.verifications);
    const supported = verifs.filter(v => v.status === 'supported').length;
    const contradicted = verifs.filter(v => v.status === 'contradicted').length;
    const unverified = verifs.filter(v => v.status === 'unverified' || v.status === 'mixed').length;

    const summaryText = [
      `This report analyzed ${claims.length} claim${claims.length !== 1 ? 's' : ''} extracted from the provided text using the ${result.provider} provider.`,
      verifs.length > 0
        ? `Of ${verifs.length} claim${verifs.length !== 1 ? 's' : ''} verified: ${supported} supported, ${contradicted} contradicted, ${unverified} unverified or partially supported.`
        : 'No claims were selected for verification (insufficient factual claims of sufficient importance).',
      `Overall risk assessment: ${result.overallRisk.toUpperCase()} — ${riskColor(result.overallRisk)}.`,
    ].join(' ');

    doc.font('Helvetica').fontSize(11).fillColor(DARK)
      .text(summaryText, 50, doc.y, { width: doc.page.width - 100, lineGap: 4 });

    if (result.ruleFindings.length > 0) {
      doc.moveDown(0.5);
      doc.font('Helvetica').fontSize(11).fillColor(DARK)
        .text(`${result.ruleFindings.length} rule finding${result.ruleFindings.length !== 1 ? 's' : ''} were detected (PII, bias, toxicity, or security patterns).`, 50, doc.y, { width: doc.page.width - 100 });
    }

    // ── CLAIMS TABLE ────────────────────────────────────────────────────────
    doc.moveDown(1.5);
    doc.font('Helvetica-Bold').fontSize(16).fillColor(DARK)
      .text('Claim Analysis', 50);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);

    if (claims.length === 0) {
      doc.font('Helvetica').fontSize(11).fillColor(GRAY)
        .text('No claims were extracted from the provided text.', 50);
    } else {
      // Table header
      const col = { claim: 50, verdict: 300, source: 400 };
      const headerY = doc.y;
      doc.rect(50, headerY, doc.page.width - 100, 18).fill('#f3f4f6');
      doc.font('Helvetica-Bold').fontSize(9).fillColor(GRAY);
      doc.text('CLAIM', col.claim + 4, headerY + 4);
      doc.text('VERDICT', col.verdict + 4, headerY + 4);
      doc.text('SOURCE', col.source + 4, headerY + 4);
      doc.moveDown(0.2);

      let rowY = headerY + 22;
      for (const claim of claims) {
        if (rowY > doc.page.height - 100) {
          doc.addPage();
          doc.rect(0, 0, doc.page.width, 8).fill(BRAND_BLUE);
          rowY = 60;
        }

        const verif = result.verifications[claim.id];
        const verdict = verif ? statusToVerdict(verif.status) : '—';
        const source = verif?.sources?.[0]?.title?.substring(0, 35) ?? '—';
        const verdictColor = verif?.status === 'supported' ? GREEN
          : verif?.status === 'contradicted' ? RED
          : GRAY;

        const claimText = claim.text.length > 80
          ? claim.text.substring(0, 77) + '...'
          : claim.text;

        // Row separator
        doc.moveTo(50, rowY - 2).lineTo(doc.page.width - 50, rowY - 2).strokeColor('#f3f4f6').stroke();

        doc.font('Helvetica').fontSize(8.5).fillColor(DARK)
          .text(claimText, col.claim, rowY, { width: 240 });
        doc.font('Helvetica-Bold').fontSize(8.5).fillColor(verdictColor)
          .text(verdict, col.verdict, rowY, { width: 90 });
        doc.font('Helvetica').fontSize(8.5).fillColor(GRAY)
          .text(source, col.source, rowY, { width: 110 });

        rowY += 18;
      }
    }

    // Footer on last page
    doc.rect(0, doc.page.height - 30, doc.page.width, 30).fill('#f9fafb');
    doc.font('Helvetica').fontSize(9).fillColor(GRAY)
      .text('Generated by Faultline Pro — faultline.nxtg.ai', 0, doc.page.height - 20, { align: 'center' });

    doc.end();
  });
}

export async function reportRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.post<{ Body: ReportBody }>(
    '/scan/report',
    {
      preHandler: requireApiKey,
      schema: { tags: ['Reports'], summary: 'Generate PDF compliance report from scan result', body: BODY_SCHEMA },
    },
    async (request, reply) => {
      const { text, provider, projectName } = request.body;
      const scanDate = new Date().toISOString().split('T')[0];

      try {
        const result = await scan(text, provider);
        const pdf = await buildPdf(result, projectName ?? 'Faultline Scan', scanDate);

        return reply
          .status(200)
          .header('Content-Type', 'application/pdf')
          .header('Content-Disposition', `attachment; filename="faultline-report-${scanDate}.pdf"`)
          .send(pdf);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return reply.status(500).send({ error: message });
      }
    },
  );
}
